### ISSUE TITLE
Genie hangs and times out.

### ISSUE THREAD

**Issue by HTD** [arkane-systems/genie#164]
**Windows version (build number):**
Windows 10 Build 21376.co_release.210503-1432

**Linux distribution:**
Ubuntu 20.04.2 LTS

**Genie version:**
1.41

**Describe the bug**
The `wsl genie -s` (and other options as well) waits until timed out. After timed out it seems like it was a root console opened, however it doesn't work normally. After pressing Ctrl+D a normal shell is started.
The shell seems to work normally and `systemctl` works there.

**If the bug involves `systemctl` or a service running under systemd, confirm that you are running inside the bottle:**
Inside

**To Reproduce**
```
wsl --shutdown
wsl genie -s
```

**Expected behavior**
WSL starts after a couple of seconds. Or: WSL starts, times out and then displays an error. Neither happens.

WSL hangs. Then displays something that looks like a root prompt. Then, after that console is exited with Ctrl+D shows the actual error message.

`systemctl list-units --failed` returns:
```
  UNIT                       LOAD   ACTIVE SUB    DESCRIPTION
● systemd-remount-fs.service loaded failed failed Remount Root and Kernel File Systems
```
However, `systemd-remount-fs.service` seems not enabled at all. There is not even such file in /etc/systemd/system.

This is WSL 2, and it has problems with my BitLocker encrypted disk, so I disabled automount feature in /etc/wsl.conf. I don't need my windows disks in my WSL. All I need is systemd working to test my .NET service I develop.

**Comment by royw** [comment]
Very similar to what I'm seeing after doing a apt upgrade this morning:
➤ genie --version
1.41
➤ genie -s
Waiting for systemd....!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!15:14:22root@****-wsl:/mnt/c/Users/royw [Python 3.8.5]
➤ logout


Timed out waiting for systemd to enter running state.
This may indicate a systemd configuration error.
Attempting to continue.
Failed units will now be displayed (systemctl list-units --failed):
  UNIT                 LOAD   ACTIVE SUB    DESCRIPTION
● avahi-daemon.service loaded failed failed Avahi mDNS/DNS-SD Stack
● gpu-manager.service  loaded failed failed Detect the available GPUs and deal with any system changes
● lightdm.service      loaded failed failed Light Display Manager

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

3 loaded units listed.
...
➤

**Comment by cerebrate** [comment]
Yeah, there's a bit of a regression there. Working on it - shouldn't be long.

As for your systemd-remount-fs problem, @HTD, that's most likely the one documented here:

https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL#systemd-remount-fsservice

**Comment by cerebrate** [comment]
Give 1.42 a try. Should hopefully be fixed.

**Comment by HTD** [comment]
Error reporting fixed. But still times out on the same error message.

**Comment by cerebrate** [comment]
@HTD The systemd-remount-fs issue? Did you check the wiki page I linked above re that one? It's a known issue (with documented fix[es]) on a number of distros including Ubuntu because the WSL-provided environment doesn't quite match that of a native Linux system.

@royw Excluding the reporting problem that should be fixed for you, too, in 1.42, gpu-manager is probably failing because of WSL not providing direct hardware access and lightdm due to lack of support for a graphical desktop session, even with WSLg; not much you can do about those except disable them (and/or switch the systemd default target to multi-user.target rather than graphical.target).

Not sure about avahi-daemon, as I've seen that one work properly before.

**Comment by HTD** [comment]
Yes, I've read it. But doesn't solve the problem. My `/etc/fstab` is empty, and I don't know whether WSL 2 automounting feature is configurable to disable mounting of particular partitions. My problem is specific to my system - I have a BitLocker encrypted drive in my system. It is locked all the time, it is unlocked only when it's used. The problem is I don't need and I don't want any of my drives to be mounted in my WSL. I changed the `/etc/wsl.conf` to disable automount feature, and it's weird, I got no error messages while starting WSL normally, but I get described error message while starting with `wsl genie -s`.

**Comment by cerebrate** [comment]
That's not an error message you'd get from the WSL automount feature, which is over and done with before genie starts systemd. An issue with a Windows drive like that isn't going to give you systemd-specific errors.

On Linux, the failing unit serves to fix any permissions issues from pre-mounts before the whole system comes up, and would normally only affect /, /usr, or virtual fsen such as /proc - see the systemd-remount-fs(8) man page for details.

Let's see what it thinks its issue is - can you send me the output of `systemctl status systemd-remount-fs`, please?

**Comment by HTD** [comment]
```
systemd-remount-fs.service - Remount Root and Kernel File Systems
     Loaded: loaded (/lib/systemd/system/systemd-remount-fs.service; enabled-runtime; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-05-13 15:08:46 CEST; 2h 41min ago
       Docs: man:systemd-remount-fs.service(8)
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
    Process: 57 ExecStart=/lib/systemd/systemd-remount-fs (code=exited, status=1/FAILURE)
   Main PID: 57 (code=exited, status=1/FAILURE)

May 13 15:08:46 CodeDog1-wsl systemd-remount-fs[63]: mount: /: can't find LABEL=cloudimg-rootfs.
Warning: journal has been rotated since unit was started, output may be incomplete.
```

**Comment by cerebrate** [comment]
Yeah, that's exactly the error message I'd expect to see from the problem described on the wiki; it's failing trying to remount the rootfs. Your /etc/fstab is definitely zero-bytes empty? If so, have you tried labeling the device backing your root fs cloudimg-rootfs anyway?

**Comment by chungktran** [comment]
I fixed the hanging issue by running the follow commands and restarted WSL with `wsl --shutdown`. I could have deleted them but prefer to rename instead. Once done that `genie -s` works fine.

```shell
sudo mv /usr/lib/systemd/system/systemd-modules-load.service /usr/lib/systemd/system/systemd-modules-load.bak
sudo mv /usr/lib/systemd/system/systemd-remount-fs.service /usr/lib/systemd/system/systemd-remount-fs.bak
```
