### ISSUE TITLE
PR: Genie for Fedora33 distro. Is there some chance to get it?

### ISSUE THREAD

**Issue by PavelSosin-320** [arkane-systems/genie#98]
I have Fedora33 WSL distro installed on my machine with all genie dependencies, i.e 
dotnet-sdk 5.0, 
unshare from util-linux 2.36.1 
daemonize, version 1.7.7. 
systemctl --version
systemd 246 (v246.7-2.fc33)
Does any chance to have genie systemd installable using DNF as I have for Ubuntu Groovy using apt-get?
I see a merged pull requested that says that it already works for "remix" version.
It will be very helpful because Podman 3.0 is just released for Fedora33 but can't work without its group manager  - systemd

**Comment by cerebrate** [comment]
I'd very much like to have a dnf/yum/rpm package available for Fedora, et al., but unfortunately for me the problem is time - I'm not familiar with that packaging method or its tools, and so far, I just don't have enough of it to learn all the tools and test against all the distros that people want. ☹️ 

I'm still hoping to find volunteer maintainers for all the non-apt package types out there!

I've attached an rpm package -

[systemd-genie-1.32-2.x86_64.rpm.gz](https://github.com/arkane-systems/genie/files/5844904/systemd-genie-1.32-2.x86_64.rpm.gz)

- translated from the apt package using _alien(1p)_ , which should work on Fedora in theory. If that doesn't work for you, the [build-it-yourself option](https://github.com/arkane-systems/genie#or-build-it-yourself) is probably the easiest approach for now.

Good luck!

**Comment by PavelSosin-320** [comment]
No problem! I have genie in Fedora. 
1st of all - install dotNet 5.0 runtime in Fedora33
Using my Ubuntu distro I downloaded the Genie's deb file, extracted its content using [dpkg-deb extract](https://unix.stackexchange.com/questions/138188/easily-unpack-deb-edit-postinst-and-repack-deb#:~:text=The%20primary%20command%20to%20manipulate,b%20to%20rebuild%20the%20package.)
and t
![Cross-distro genie](https://user-images.githubusercontent.com/54495912/106376502-9a524e80-639e-11eb-8f2e-4e219b4ca600.png)
hen I copied the "essential" files to the Windows Program files, made them executable chmod+x and add my new "Genie Windows directory to the Windows PATH.
Then I created Desktop shortcut with wsl -d Fedora33 -u root. Now I can run Fedora 33 distro clicking on the "Fedora" icon.

**Comment by gbraad** [comment]
Issues occur when the machine is used as a basic desktop and a regular user:

```
Error registering authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject (polkit-error-quark, 0)
Failed to start systemd-modules-load.service: Interactive authentication required.
See system logs and 'systemctl status systemd-modules-load.service' for details.
```

**Comment by gbraad** [comment]
@cerebrate Will create an RPM package for this. Will you re-open?

**Comment by cerebrate** [comment]
@gbraad I'd certainly like to have an RPM package available, especially if it can generalize across popular RPM-based distros.

Before I action this - are you looking at creating a one-time RPM package for this, or effectively volunteering as ~~tribute~~ RPM maintainer? Or somewhere in between?

**Comment by gbraad** [comment]
A package, automated setup at fedora and hopefully can maintain it long-term (but there has been interest, so likely can find maintainers from the community too).

**Comment by PavelSosin-320** [comment]
@gbraad I installed genie "cross-distro" in the following way:  I downloaded the genie apt package to the Ubuntu distro and unpacked it.
Then I copied the 'essential" genie files, i.e. genie executive and all scripts to the Windows' Program Files\genie and added them to the Widows' Path. Every distro inherits Windows's path and it makes genie available for every Linux distro. Microsoft itself distributes DotNet. It is not a dependency that resolved by apt or dnf.  Hopefully, genie has no distro-specific dependencies than Systemd already installed with distro installation, DotNet, and kernel.  The problem is that I need to repeat this procedure for every genie update using 2 distros. What I need is the zip or tar that can be extracted directly into Program Files \ genie.
In all cases, WSL distros share the same Microsoft's Kernel by default. Also, .wslconfig is shared by all distros unless a custom Kernel is used. It will be perfect to provide a .wslconfig [wsl] section that covers the most common scenario with few lines of documentation.

**Comment by gbraad** [comment]
Using `alien` or `ar x` is a bad practice as when a binary is dynamically linked this can cause issues. Luckily for .net they get statically compiled.

**Comment by gbraad** [comment]
Other dependencies are machinectl and daemonize. The former is not a regular installed package; it only comes with the nspawn package.

**Comment by cerebrate** [comment]
@gbraad Great stuff!

I don't think we need to reopen in this issue, but if you let me know the details when you're ready, and I'll add them to the installation README so people know where to go to get it. Or just send me a PR, either way.

**Comment by cerebrate** [comment]
@PavelSosin-320 Impressed as I am that you got genie to work that way, I confess to being a mite horrified at the thought of having to support it, and distro differences are definitely one reason.

(And while .NET is shipped by Microsoft, it's shipped as an apt package, so apt is certainly useful when it comes to managing that dependency, even if it doesn't resolve it without user intervention.)

**Comment by gbraad** [comment]
@cerebrate I created a `.spec` file to create an RPM package. I published a test version at:

 * https://github.com/gbraad/fedora-wsl-genie/releases/tag/1.34

Still some minor changes that can be made, but works as-is.

**Comment by milesbuckton** [comment]
```ini
 [genie]
 systemd-timeout=5
```
Thanks for the additional info. :) I had to set the timeout to a minimum of 90 seconds, otherwise `genie-s` failed.

**Comment by milesbuckton** [comment]
@gbraad, I now have a Gnome 3 WSL2 desktop on Fedora thanks to your superb instructions above! 🎉 See the screenshots on my comment: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/82#issuecomment-781264966

**Comment by gbraad** [comment]
@milesbuckton

Please check with
```
$ genie -s
$ systemctl list-units --failed
```

what didn't work. Sometimes it is easy to solve, or otherwise I can mask them beforehand in an updated package

**Comment by gbraad** [comment]
I also compiled the `RunInGenie` app to allow easy WSL invocation from PowerShell. I put up a PR for a containerized build here: https://github.com/arkane-systems/RunInGenie/pull/1

**Comment by milesbuckton** [comment]
> systemctl list-units --failed

@gbraad, this is the error I get if I use a timeout of 30 seconds for example.
![Error](https://user-images.githubusercontent.com/37063023/108466979-2e705100-728d-11eb-896d-43e6d0b52314.png)

**Comment by gbraad** [comment]
Did you install the RPM ?
It seems you are perhaps missing the machinectl command. This is provided by systemd-container. Can you verify?

**Comment by milesbuckton** [comment]
@gbraad, yes - I did install the `systemd-container` rpm package.

**Comment by cerebrate** [comment]
@milesbuckton Can we get a `ps aux` after the failed startup? Let's see what's actually running in there.

**Comment by gbraad** [comment]
the `no bus` would indicate it tries to look for a dbus endpoint, which is not there... 
has other things been changed on this WSL install before to make things work?

**Comment by milesbuckton** [comment]
> @milesbuckton Can we get a `ps aux` after the failed startup? Let's see what's actually running in there.

@cerebrate, this is what I get before the fail and after it works:

![Fail](https://user-images.githubusercontent.com/37063023/108470221-4c8c8000-7292-11eb-842e-bb2310f144c6.png)

![Pass](https://user-images.githubusercontent.com/37063023/108470225-4e564380-7292-11eb-8dc3-3f9f0b701c66.png)

**Comment by gbraad** [comment]
what is the target you are using... `graphical`? I do not run plymouth for instance... as this looks VERY bare to start with.
the second image is when you start the second session and things worked?

**Comment by milesbuckton** [comment]
> the `no bus` would indicate it tries to look for a dbus endpoint, which is not there...
> has other things been changed on this WSL install before to make things work?

Not really. It only happens if the timeout is less than what is "comfortable" my PC.

**Comment by milesbuckton** [comment]
> what is the target you are using... `graphical`? I do not run plymouth for instance... as this looks VERY bare (like nothing actually started).
> the second image is when you start the second session and things worked?

Yes, the second image is after I close the tab, and reopen another one (session).

**Comment by gbraad** [comment]
for me it takes about ~2s on a cold start, but I am on an SSD and a well specced machine.
Though I would wonder, for starting you might need to wait a lot longer... or perhaps one of the units times out before starting the rest?

**Comment by gbraad** [comment]
in the second tab, what is the output of `systemctl list-units --failed` or it also fails there?

**Comment by milesbuckton** [comment]
> for me it takes about ~2s on a cold start, but I am on an SSD and a well specced machine.
> Though I would wonder, for starting you might need to wait a lot longer... or perhaps one of the units times out before starting the rest?

My laptop is an Intel i9 with 32GB of RAM, and an SSD: so it shouldn't be the laptop specs.
It could be.

**Comment by milesbuckton** [comment]
> in the second tab, what is the output of `systemctl list-units --failed` or it also fails there?

![Output](https://user-images.githubusercontent.com/37063023/108471059-8ad66f00-7293-11eb-8dcb-f6539da47336.png)

**Comment by cerebrate** [comment]
The second tab isn't a success either, FYI: look at the pid of systemd (69, not 1). You're still outside the bottle.

Also, yes, that looks like a very minimalist startup, with maybe... 3 services running? None of which is systemd-machined, which is why `genie -s` is failing.

**Comment by cerebrate** [comment]
You can manually get into the bottle with `sudo nsenter -t 69 -m -p /bin/bash` . (Use the systemd pid instead of 69 if it's changed.) That should give you more reliable access to `systemctl` and other systemd-requiring things. Once there, since you have `systemd-container` installed, you should be able to `systemctl enable systemd-machined`.

Having done that, then if you shutdown and restart WSL and genie, it should work properly. Hopefully.

**Comment by milesbuckton** [comment]
@cerebrate, this is what I got after I ran the commands.

![Systemd](https://user-images.githubusercontent.com/37063023/108472608-a6db1000-7295-11eb-97f3-053d0514d4e7.png)

![Output](https://user-images.githubusercontent.com/37063023/108472797-e30e7080-7295-11eb-99cb-35befe127c34.png)

**Comment by gbraad** [comment]
The second and last image look as expected:

Can you do:
```
$ sudo systemctl disable auditd
$ sudo journalctl -u dbus-daemon
```

Besides... what is the different between these images... just waiting?

**Comment by gbraad** [comment]
BTW @milesbuckton what is the `systemctl get-default` ? Not sure why machined wasn't started on your machine

**Comment by milesbuckton** [comment]
![Start](https://user-images.githubusercontent.com/37063023/108474209-bbb8a300-7297-11eb-9fad-035c985c55b8.png)

![Target](https://user-images.githubusercontent.com/37063023/108474215-bd826680-7297-11eb-83c4-95b3f5b9f8dd.png)

**Comment by gbraad** [comment]
Do perform the command from within the bottle (`genie -s`)
```
$ sudo systemctl disable auditd
```

else it will fail with the error you see.

**Comment by milesbuckton** [comment]
Ok, that worked now for disabling the service:

![Disable](https://user-images.githubusercontent.com/37063023/108474906-ae4fe880-7298-11eb-8285-34e67553973d.png)

**Comment by gbraad** [comment]
For me it would show the same if I start it:
```
$ sudo systemctl start dbus-daemon
$ journalctl -u dbus-daemon
-- Logs begin at Sat 2021-02-13 23:07:36 CST, end at Fri 2021-02-19 15:56:52 CST. --
Feb 19 15:56:52 WinT14-wsl systemd[1]: Started D-Bus System Message Bus.
Feb 19 15:56:52 WinT14-wsl dbus-daemon[509]: Failed to start message bus: No socket received.
Feb 19 15:56:52 WinT14-wsl systemd[1]: dbus-daemon.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 15:56:52 WinT14-wsl systemd[1]: dbus-daemon.service: Failed with result 'exit-code'.
```
might have a look at this as I am not sure why it would fail.

**Comment by milesbuckton** [comment]
Yes, I get the same:

![image](https://user-images.githubusercontent.com/37063023/108475275-2a4a3080-7299-11eb-9325-bd6eb56f934a.png)

Thanks for all your help guys. 👍

**Comment by gbraad** [comment]
BTW, the reason why `auditd` does not work
```
-- Reboot --
Feb 14 00:03:46 WinT14-wsl systemd[1]: Starting Security Auditing Service...
Feb 14 00:03:46 WinT14-wsl auditd[129]: Error - audit support not in kernel
Feb 14 00:03:46 WinT14-wsl auditd[129]: Cannot open netlink audit socket
Feb 14 00:03:46 WinT14-wsl auditd[129]: The audit daemon is exiting.
Feb 14 00:03:46 WinT14-wsl auditd[127]: Cannot daemonize (Success)
Feb 14 00:03:46 WinT14-wsl auditd[127]: The audit daemon is exiting.
Feb 14 00:03:46 WinT14-wsl systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
Feb 14 00:03:46 WinT14-wsl systemd[1]: auditd.service: Failed with result 'exit-code'.
Feb 14 00:03:46 WinT14-wsl systemd[1]: Failed to start Security Auditing Service.
Feb 14 00:10:27 WinT14-wsl systemd[1]: Starting Security Auditing Service...
Feb 14 00:10:27 WinT14-wsl auditd[129]: Error - audit support not in kernel
Feb 14 00:10:27 WinT14-wsl auditd[129]: Cannot open netlink audit socket
Feb 14 00:10:27 WinT14-wsl auditd[129]: The audit daemon is exiting.
Feb 14 00:10:27 WinT14-wsl auditd[127]: Cannot daemonize (Success)
Feb 14 00:10:27 WinT14-wsl auditd[127]: The audit daemon is exiting.
Feb 14 00:10:27 WinT14-wsl systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
Feb 14 00:10:27 WinT14-wsl systemd[1]: auditd.service: Failed with result 'exit-code'.
Feb 14 00:10:27 WinT14-wsl systemd[1]: Failed to start Security Auditing Service.
```

Which states:
`Feb 14 00:10:27 WinT14-wsl auditd[129]: Error - audit support not in kernel`
so this would never work with the current kernel.

**Comment by gbraad** [comment]
I am not an expert for this, but I believe `dbus-socket` should result in an `fd` that should be handed to the dbus-daemon; hence the `Failed to start message bus: No socket received.` No idea why this happens, as there is a `/var/run/dbus/system_bus_socket` active.

**Comment by gbraad** [comment]
I see:
```
$ systemctl status dbus
● dbus-broker.service - D-Bus System Message Bus
     Loaded: loaded (/usr/lib/systemd/system/dbus-broker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-02-19 15:52:14 CST; 48min ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-broker-launch(1)
   Main PID: 147 (dbus-broker-lau)
      Tasks: 2 (limit: 30555)
     Memory: 4.0M
     CGroup: /system.slice/dbus-broker.service
             ├─147 /usr/bin/dbus-broker-launch --scope system --audit
             └─164 dbus-broker --log 4 --controller 9 --machine-id f60cfac8d6864901a41d26b835fedf19 --max-bytes 536870912 --max-fds 4096 --max-matches 131072 --audit

Feb 19 15:52:14 WinT14-wsl systemd[1]: Starting D-Bus System Message Bus...
Feb 19 15:52:14 WinT14-wsl systemd[1]: Started D-Bus System Message Bus.
Feb 19 15:52:14 WinT14-wsl dbus-broker-lau[147]: Ready
```
while:
```
$ systemctl status dbus-daemon
● dbus-daemon.service - D-Bus System Message Bus
     Loaded: loaded (/usr/lib/systemd/system/dbus-daemon.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2021-02-19 16:29:10 CST; 12min ago
       Docs: man:dbus-daemon(1)
    Process: 765 ExecStart=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only (code=exited, status=1/FAILURE)
   Main PID: 765 (code=exited, status=1/FAILURE)

Feb 19 16:29:10 WinT14-wsl systemd[1]: Started D-Bus System Message Bus.
Feb 19 16:29:10 WinT14-wsl dbus-daemon[765]: Failed to start message bus: No socket received.
Feb 19 16:29:10 WinT14-wsl systemd[1]: dbus-daemon.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 16:29:10 WinT14-wsl systemd[1]: dbus-daemon.service: Failed with result 'exit-code'.
$                                                                                     
```
Anyone any ideas around this?

**Comment by cerebrate** [comment]
It's getting a bit beyond my knowledge, I'm afraid, but what does `systemctl status dbus.socket` - i.e., for the socket rather than the service it triggers - look like? Mine shows:

```
● dbus.socket - D-Bus System Message Bus Socket
     Loaded: loaded (/lib/systemd/system/dbus.socket; static)
     Active: active (running) since Fri 2021-02-19 11:39:54 CST; 12min ago
   Triggers: ● dbus.service
     Listen: /run/dbus/system_bus_socket (Stream)
     CGroup: /system.slice/dbus.socket

Feb 19 11:39:54 athena-wsl systemd[1]: Listening on D-Bus System Message Bus Socket.
```

but hopefully any problems systemd is having with the socket itself should show up there.

**Comment by tjehlar** [comment]
> 
> 
> It's getting a bit beyond my knowledge, I'm afraid, but what does `systemctl status dbus.socket` - i.e., for the socket rather than the service it triggers - look like? Mine shows:
> 
> ```
> ● dbus.socket - D-Bus System Message Bus Socket
>      Loaded: loaded (/lib/systemd/system/dbus.socket; static)
>      Active: active (running) since Fri 2021-02-19 11:39:54 CST; 12min ago
>    Triggers: ● dbus.service
>      Listen: /run/dbus/system_bus_socket (Stream)
>      CGroup: /system.slice/dbus.socket
> 
> Feb 19 11:39:54 athena-wsl systemd[1]: Listening on D-Bus System Message Bus Socket.
> ```
> 
> but hopefully any problems systemd is having with the socket itself should show up there.

I am having the same issue as the other user, and unfortunately that would not seem to be providing useful information:
`● dbus.socket - D-Bus System Message Bus Socket
     Loaded: loaded (/usr/lib/systemd/system/dbus.socket; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-02-26 23:26:27 PST; 5min ago
   Triggers: ● dbus-broker.service
     Listen: /run/dbus/system_bus_socket (Stream)
     CGroup: /system.slice/dbus.socket

Feb 26 23:26:27 TRISTAN-MACBOOKPRO-wsl-wsl systemd[1]: Listening on D-Bus System Message Bus Socket.`

**Comment by PavelSosin-320** [comment]
@tjehlar I currently use Fedora34 distro installed following Fedora magazine recommendations with genie 1.35.Everything looks OK except degraded status due to systemd-oomd.service startup failure. But the last looks as known Fedora34 issue. [Fedora bug 1926373.](https://bugzilla.redhat.com/show_bug.cgi?id=1926373). Podman 3.0 still has some problem in the rootless mode.

**Comment by gbraad** [comment]
@tjehlar what is the usecase that the `dbus-service` unit is started?
I noticed that a generic headless setup has no issues, hence the 'report' that it works for F34.
